Alpha: 100
Categorical_Features:
- vendor_id
- passenger_count
- store_and_fwd_flag
- hour
- day
- dayofweek
- month
- Season
Numerical_Features:
- pickup_longitude
- pickup_latitude
- dropoff_longitude
- dropoff_latitude
- distance_haversine
- direction
- distance_manhattan
Polynomial_Degree: 5
Scaler: StandardScaler
model_type: RidgeRegression
