Alpha: 100
Categorical_Features:
- passenger_count
- store_and_fwd_flag
- hour_period_bin
- dayofweek
- day
- dayofyear_bin
- month
- season
Numerical_Features:
- distance_haversine
- distance_manhattan
Polynomial_Degree: 6
Scaler: StandardScaler
model_path: Models/Ridge_Model.pkl
model_type: RidgeRegression
